language: go

go:
  - "1.12"

env:
  - DEP_VERSION="0.5.2" OPERATOR_SDK_VERSION="v0.8.1"

before_install:
  # if we're in a mainline build, don't make a symlink
  # if we're not in a mainline build, symlink the proper dir to point to this dir.
  - if [["github.com/BlueK8S" in $(TRAVIS_BUILD_DIR)]]; then echo "mainline build, no symlink"; else mkdir -p $GOPATH/src/github.com/BlueK8S && ln -s $(pwd) $GOPATH/src/github.com/BlueK8S/kubedirector ; fi
  # Get dep
  - curl -L -s https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Get the K8s operator-sdk
  - curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu -o $GOPATH/bin/operator-sdk
  - chmod +x $GOPATH/bin/operator-sdk
  - go get -u golang.org/x/lint/golint
  - make dep

script:
  - make compile
  - make golint
  - make check-format
