apiVersion: "kubedirector.bluedata.io/v1alpha1"
kind: "KubeDirectorConfig"
metadata:
  name: "kd-global-config"
spec:
  defaultStorageClassName: "do-block-storage"
  defaultServiceType: "LoadBalancer"
