#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: ldapsecret
#  labels:
#    kubedirector.hpe.com/secretType: extAuth
#  data:
#    auth_type: "LDAP"
#    ssl_enabled: "False"
#    server_address: "16.143.20.82"
#    server_port: "389"
#    lookup_dn: "True"
#    user_search_base: "dc=mip,dc=storage,dc=hpecorp,dc=net"
#    user_attribute: "cn"
#    bind_user_dn: "cn=admin,dc=mip,dc=storage,dc=hpecorp,dc=net"
#    bind_dn_template: "cn={username},ou=People,dc=mip,dc=storage,dc=hpecorp,dc=net"
#    valid_username_regex: "^[A-Za-z][.@A-Za-z0-9_-]*$"
#    member_of: CN=Eng,OU=Group,DC=mip,DC=storage,DC=hpecorp,DC=net:CN=QA,OU=Group,DC=mip,DC=storage,DC=hpecorp,DC=net
---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "jupyter-notebook"
spec:
  app: jupyter-notebook
  appCatalog: "local"
#  connections:
#    secrets:
#      - "hpecp-ext-auth-secret"
#      - "hpecp-source-control-secret-d4c2c7467201788666a6347ce339fc41"
#    configmaps:
#      - "ldapsecret"
#    clusters:
#      - "training-cluster"
  roles:
  - id: controller
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
#      podLabels:
#        hpecp.hpe.com/dtap: "inject"
