apiVersion: "kubedirector.bluedata.io/v1alpha1"
kind: "KubeDirectorCluster"
metadata:
  name: "cassandra-lb-persistent"
spec:
  app: cassandra311
  serviceType: LoadBalancer
  roles:
  - id: seed
    members: 2
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    storage:
      size: "40Gi"
      storageClassName: standard
  - id: worker
    members: 2
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
    storage:
      size: "40Gi"
      storageClassName: standard
