apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "ml-jupyter-notebook"
spec:
  app: ml-jupyter-notebook
  roles:
  - id: controller
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1"        
      limits:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1"