apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorconfigs.kubedirector.bluedata.io
spec:
  group: kubedirector.bluedata.io
  names:
    kind: KubeDirectorConfig
    listKind: KubeDirectorConfigsList
    plural: kubedirectorconfigs
    singular: kubedirectorconfig
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              pattern: '^kd-global-config$'
        spec:
          properties:
            defaultStorageClassName:
              type: string
              minLength: 1
            defaultServiceType:
              type: string
              pattern: '^NodePort$|^LoadBalancer$'
            nativeSystemdSupport:
              type: boolean
