apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorclusters.kubedirector.bluedata.io
spec:
  group: kubedirector.bluedata.io
  version: v1alpha1
  names:
    kind: KubeDirectorCluster
    listKind: KubeDirectorClusterList
    plural: kubedirectorclusters
    singular: kubedirectorcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: [apiVersion, kind, metadata, spec]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          required: [app, roles]
          properties:
            app:
              type: string
              minLength: 1
            appCatalog:
              type: string
              pattern: '^local$|^system$'
            serviceType:
              type: string
              pattern: '^ClusterIP$|^NodePort$|^LoadBalancer$'
            defaultSecret:
              required: [name, mountPath]
              properties:
                name:
                  type: string
                  minLength: 1
                mountPath:
                  type: string
                  minLength: 1
                  pattern: '^/[a-zA-Z0-9\/-_]*'
                defaultMode:
                  type: integer
                  maximum: 511
                readOnly:
                  type: boolean
            roles:
              type: array
              items:
                required: [id, resources]
                properties:
                  id:
                    type: string
                    minLength: 1
                  members:
                    type: integer
                    minimum: 0
                  secret:
                    required: [name, mountPath]
                    properties:
                      name:
                        type: string
                        minLength: 1
                      mountPath:
                        type: string
                        minLength: 1
                        pattern: '^/[a-zA-Z0-9\/-_]*'
                      defaultMode:
                        type: integer
                        maximum: 511
                      readOnly:
                        type: boolean
                  resources:
                    required: [limits]
                    properties:
                      limits:
                        required: [memory, cpu]
                        properties:
                          memory:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                          cpu:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                          nvidia.com/gpu:
                            type: integer
                          amd.com/gpu:
                            type: integer
                          ephemeral-storage:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                      requests:
                        properties:
                          memory:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                          cpu:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                          ephemeral-storage:
                            type: string
                            pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                  env:
                    type: array
                    items:
                      required: [name, value]
                      properties:
                        name:
                          type: string
                          minLength: 1
                        value:
                          type: string
                  storage:
                    required: [size]
                    properties:
                      size:
                        type: string
                        pattern: '^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                      storageClassName:
                        type: string
                        minLength: 1
                  fileInjections:
                    type: array
                    items:
                      required: [srcUrl, destDir]
                      properties:
                        srcUrl:
                          type: string
                          pattern: '^https?://.+$'
                        destDir:
                          type: string
                          pattern: '^/.*$'
                          minLength: 1
                        permissions:
                          properties:
                            fileMode:
                              type: string
                            fileOwner:
                              type: string
                            fileGroup:
                              type: string
        status:
          properties:
            state:
              type: string
            generationUid:
              type: string
            clusterService:
              type: string
            lastNodeID:
              type: integer
            roles:
              type: array
              items:
                properties:
                  id:
                    type: string
                  statefulSet:
                    type: string
                  members:
                    type: array
                    items:
                      properties:
                        pod:
                          type: string
                        nodeID:
                          type: integer
                        service:
                          type: string
                        pvc:
                          type: string
                        state:
                          type: string
