apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubedirectorconfigs.kubedirector.bluedata.io
spec:
  group: kubedirector.bluedata.io
  version: v1alpha1
  names:
    kind: KubeDirectorConfig
    listKind: KubeDirectorConfigList
    plural: kubedirectorconfigs
    singular: kubedirectorconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      required: [apiVersion, kind, metadata]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: '^kd-global-config$'
        spec:
          type: object
          nullable: true
          properties:
            defaultStorageClassName:
              type: string
              minLength: 1
            defaultServiceType:
              type: string
              pattern: '^ClusterIP$|^NodePort$|^LoadBalancer$'
            nativeSystemdSupport:
              type: boolean
            requiredSecretPrefix:
              type: string
            clusterSvcDomainBase:
              type: string
        status:
          type: object
          nullable: true
          properties:
            generationUID:
              type: string
            state:
              type: string
